### ISSUE TITLE
Overcorrection of /app → /frontend

### ISSUE THREAD

**Issue by darrenkuro** [cubernetes/ft-transcendence#41]
I think there has been some oversights of replacing globally from `/app` to `/frontend`, namely working dir of Dockerfile (especially the one for backend?). Also in docker-compose, the syncing targets, for instance. I was gonna correct some back but wasn't sure what's the correct Docker volume structure that we are going for.

**Comment by cubernetes** [comment]
Yeah #38 fixes the naming issue, but what do you mean with docker compose watch being weird?

**Comment by darrenkuro** [comment]
> Yeah [#38](https://github.com/cubernetes/ft-transcendence/pull/38) fixes the naming issue, but what do you mean with docker compose watch being weird?

```
        volumes:
            - "drizzle:/frontend/drizzle/"
        develop:
            watch:
                - path: "./backend/"
                  action: sync # Might fail on MacOS when node_modules is touched, use `rebuild' as fallback
                  target: "/frontend/"
                - path: "./backend/package.json"
                  action: rebuild
                  target: "/frontend/package.json"
                - path: "./backend/esbuild.config.js"
                  action: rebuild
                  target: "/frontend/esbuild.config.js"
```
This portion, not sure if it's fixed somewhere.

**Comment by cubernetes** [comment]
Ohhh you're right, good catch! I'll make another commit in #38 tomorrow, going to sleep now. Thanks for flagging

**Comment by darrenkuro** [comment]
Changed to
```
        volumes:
             - "drizzle:/backend/drizzle/"
         develop:
             watch:
                 - path: "./backend/"
                   action: sync # Might fail on MacOS when node_modules is touched, use `rebuild' as fallback
                   target: "/backend/"
                 - path: "./backend/package.json"
                   action: rebuild
                   target: "/backend/package.json"
                 - path: "./backend/esbuild.config.js"
                   action: rebuild
                   target: "/backend/esbuild.config.js"
```
in PR #42 , should be correct as far as I can tell...
